import './oy_ui.scss'
export {default as Switch} from './Switch.vue'
export {default as Button} from './Button.vue'
export {default as Tab} from './Tab.vue'
export {default as Tabs} from './Tabs.vue'
export {default as Dialog} from './Dialog/Dialog.vue'
export {default as CollapseItem} from './Collapse/Collapse-Item.vue'
export {default as Collapse} from './Collapse/Collapse.vue'
export {OpenDialog as OpenDialog} from './Dialog/openDialog'
export {default as waveHandle} from './public_js/waveHandle'
